/*
 * lcd.h
 *
 *  Created on: 21-Mar-2026
 *      Author: sunbeam
 */

#ifndef LCD_H_
#define LCD_H_

#include "main.h"

#ifndef BV
	#define BV(n) (1 << (n))
#endif

//#define LCD_SLAVE_ADDR_W	0x4E
//#define LCD_SLAVE_ADDR_R	0x4F
#define LCD_ADDR   (0x27 << 1)   // change to 0x3F<<1 if needed
#define TOTAL_SLOTS 2

extern I2C_HandleTypeDef hi2c1;   // generated by CubeMX

extern uint8_t entryPrevState ;
extern uint8_t exitPrevState  ;
extern int8_t  parkedCount    ;       // number of cars currently parked
extern uint8_t lcdNeedsUpdate ;

void LCD_Init(void);
void LCD_SendCmd(uint8_t cmd);
void LCD_SendData(uint8_t data);
void LCD_SendString(char *str);
void LCD_SetCursor(uint8_t row, uint8_t col);
void LCD_UpdateParkingDisplay(void);
void lcd_shift_display(void);

#endif /* LCD_H_ */















