/*
 * lcd.c
 *
 *  Created on: 21-Mar-2026
 *      Author: sunbeam
 */

#include "lcd.h"

extern I2C_HandleTypeDef hi2c2;   // generated by CubeMX

uint8_t entryPrevState = 0;
 uint8_t exitPrevState  = 0;
 int8_t  parkedCount    = 0;       // number of cars currently parked
 uint8_t lcdNeedsUpdate = 1;

/* ---------- I2C LCD (PCF8574, 4-bit mode) ---------- */
void LCD_Write4Bits(uint8_t data)
{
    uint8_t buf[1];
    buf[0] = data | 0x08;               // backlight ON bit
    HAL_I2C_Master_Transmit(&hi2c2, LCD_ADDR, buf, 1, 100);
    HAL_Delay(1);
    buf[0] = data | 0x0C;               // EN=1
    HAL_I2C_Master_Transmit(&hi2c2, LCD_ADDR, buf, 1, 100);
    HAL_Delay(1);
    buf[0] = data | 0x08;               // EN=0
    HAL_I2C_Master_Transmit(&hi2c2, LCD_ADDR, buf, 1, 100);
}

void LCD_SendCmd(uint8_t cmd)
{
    uint8_t hi = cmd & 0xF0;
    uint8_t lo = (cmd << 4) & 0xF0;
    LCD_Write4Bits(hi);
    LCD_Write4Bits(lo);
}

void LCD_SendData(uint8_t data)
{
    uint8_t hi = (data & 0xF0) | 0x01;   // RS=1
    uint8_t lo = ((data << 4) & 0xF0) | 0x01;
    LCD_Write4Bits(hi);
    LCD_Write4Bits(lo);
}

void LCD_Init(void)
{
    HAL_Delay(50);
    LCD_Write4Bits(0x30); HAL_Delay(5);
    LCD_Write4Bits(0x30); HAL_Delay(1);
    LCD_Write4Bits(0x30); HAL_Delay(1);
    LCD_Write4Bits(0x20); HAL_Delay(1);   // 4-bit mode

    LCD_SendCmd(0x28);   // 4-bit, 2 line, 5x8 font
    LCD_SendCmd(0x0C);   // display ON, cursor OFF
    LCD_SendCmd(0x06);   // entry mode
    LCD_SendCmd(0x01);   // clear display
    HAL_Delay(2);
}

void LCD_SetCursor(uint8_t row, uint8_t col)
{
    uint8_t addr = (row == 0) ? (0x80 + col) : (0xC0 + col);
    LCD_SendCmd(addr);
}

void LCD_SendString(char *str)
{
    while (*str) LCD_SendData((uint8_t)(*str++));
}

/* ---------- Parking display ---------- */
//void LCD_UpdateParkingDisplay(void)
//{
//    char line2[17];
//    int8_t available = TOTAL_SLOTS - parkedCount;
//    if (available < 0) available = 0;
//
//    LCD_SetCursor(0, 0);
//    LCD_SendString("Welcome Parking ");   // 16 chars incl. padding
//
//    snprintf(line2, sizeof(line2), "Tot:%2d Avl:%2d  ", TOTAL_SLOTS, available);
//    LCD_SetCursor(1, 0);
//    LCD_SendString(line2);
//}

void LCD_UpdateParkingDisplay(void)
{
    char buf[17];

    LCD_SendCmd(0x01);      // Clear LCD
    HAL_Delay(2);

    LCD_SetCursor(0,0);
    sprintf(buf,"Total:%d", TOTAL_SLOTS);
    LCD_SendString(buf);

    LCD_SetCursor(1,0);

    if(parkedCount >= TOTAL_SLOTS)
    {
        LCD_SendString("Parking Full");
    }
    else
    {
        sprintf(buf,"Available:%d", TOTAL_SLOTS - parkedCount);
        LCD_SendString(buf);
    }
}
